name: PR Preview

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      FAIL_ON_WARNING: "true" # Set this to 'false' to not fail the build on warnings

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install LaTeX
        run: sudo apt-get install texlive-full

      - name: Compile LaTeX document
        id: compile
        run: |
          pdflatex -interaction=nonstopmode -halt-on-error main.tex || echo "compilation failed" >> compile.flag
        continue-on-error: true

      - name: Upload PDF if build is successful
        if: success() && !contains(steps.compile.outputs, 'compilation failed')
        uses: actions/upload-artifact@v2
        with:
          name: pr-preview
          path: main.pdf

      - name: Check for Warnings and Errors
        id: logcheck
        run: |
          errors=$(grep -i "error" *.log || true)
          warnings=$(grep -i "warning" *.log || true)
          echo "::set-output name=errors::$errors"
          echo "::set-output name=warnings::$warnings"
          if [ -n "$errors" ]; then
            echo "Errors found in log."
            echo "::set-output name=status::failed"
          elif [ -n "$warnings" ] && [ "${{ env.FAIL_ON_WARNING }}" == "true" ]; then
            echo "Warnings found in log."
            echo "::set-output name=status::failed"
          else
            echo "No critical issues found."
            echo "::set-output name=status::success"
          fi

      - name: Comment build result on PR
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Build results:
            <details>
              <summary>Click to expand errors</summary>
            
              ```
              ${{ steps.logcheck.outputs.errors }}
              ```
            </details>
            <details>
              <summary>Click to expand warnings</summary>
            
              ```
              ${{ steps.logcheck.outputs.warnings }}
              ```
            </details>
            ${{ if eq(steps.logcheck.outputs.status, 'failed') }}
            Build failed.
            ${{ else }}
            [Download the compiled PDF](https://github.com/${{ github.repository }}/actions/artifacts/${{ github.run_id }}?artifactName=pr-preview)
            ${{ endif }}

      - name: Fail the job if there were errors or warnings
        if: steps.logcheck.outputs.status == 'failed'
        run: exit 1
