name: PR Preview

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    name: Build Preview
    runs-on: ubuntu-latest
    container: laurenss/texlive-full

    env:
      FAIL_ON_WARNING: "true"  # Set this to 'false' to not fail the build on warnings

    steps:
      - uses: actions/checkout@v3

      - name: Setup Variables
        id: vars
        run: |
          echo "artifact-name=preview#${{ github.event.pull_request.number }}.$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Install Dependencies
        run: |
          apt-get install python3-pip
          pip3 install pygments
          apt-get install inkscape

      - name: Compile Document
        id: compile
        run: |
          pdflatex --shell-escape -interaction=nonstopmode -halt-on-error main.tex
          makeglossaries main
          pdflatex --shell-escape -interaction=nonstopmode -halt-on-error main.tex
          pdflatex --shell-escape -interaction=nonstopmode -halt-on-error main.tex
        continue-on-error: true

      - name: Upload Artifacts
        id: pdf-upload
        if: ${{ steps.compile.outcome == 'success' }}
        uses: actions/upload-artifact@v4.3.3
        with:
          name: ${{ steps.vars.outputs.artifact-name }}
          path: |
            main.pdf
            *.log
            *.aux

      - name: Generate Report
        run: python .github/workflows/generate_comment.py ${{ steps.pdf-upload.outputs.artifact-url }}

      - name: Publish Report
        uses: peter-evans/create-or-update-comment@v3.1.0
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body-path: comment_body.md

      - name: Analyze Logs
        run: python .github/workflows/check_logs.py
