name: PR Preview

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  Build-Preview:
    name: build
    runs-on: ubuntu-latest

    env:
      FAIL_ON_WARNING: "true"  # Set this to 'false' to not fail the build on warnings

    steps:
      - uses: actions/checkout@v3

      - name: Generate Artifact Name
        id: vars
        run: echo "artifact_name=preview#${{ github.event.pull_request.number }}.$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Get hash of workflow file
        id: workflow-hash
        run: echo "::set-output name=hash::$(sha256sum .github/workflows/this_workflow.yml | awk '{ print $1 }')"

      - name: Cache LaTeX packages
        uses: actions/cache@v3
        with:
          path: |
            /usr/local/share/texmf
            /usr/share/texlive
          key: ${{ runner.os }}-texlive-${{ steps.workflow-hash.outputs.hash }}
          restore-keys: |
            ${{ runner.os }}-texlive-

      - name: Install LaTeX
        run: |
          if ! command -v pdflatex &> /dev/null
          then
            sudo apt-get install texlive-full texlive-xetex texlive-latex-extra texlive-bibtex-extra
          fi

      - name: Install pygments
        uses: BSFishy/pip-action@v1
        with:
          packages: pygments

      - name: Install inkscape
        run: sudo apt-get install inkscape

      - name: Compile Document
        id: compile
        run: |
          pdflatex --shell-escape -interaction=nonstopmode -halt-on-error main.tex
          makeglossaries main
          pdflatex --shell-escape -interaction=nonstopmode -halt-on-error main.tex
          pdflatex --shell-escape -interaction=nonstopmode -halt-on-error main.tex
        continue-on-error: true

      - name: Upload Artifacts
        id: pdf-upload
        if: ${{ steps.compile.outcome == 'success' }}
        uses: actions/upload-artifact@v4.3.3
        with:
          name: ${{ steps.vars.outputs.artifact_name }}
          path: |
            main.pdf
            *.log
            *.aux

      - name: Generate Report
        run: python .github/workflows/generate_comment.py ${{ steps.pdf-upload.outputs.artifact-url }}

      - name: Generate Report
        run: python .github/workflows/generate_comment.py ${{ steps.pdf-upload.outputs.artifact-url }}

      - name: Publish Report
        uses: peter-evans/create-or-update-comment@v3.1.0
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body-path: comment_body.md

      - name: Analyze Logs
        run: python .github/workflows/check_logs.py
