name: Build and Release PDF on push

on:
  push:
    branches:
      - main

jobs:
    build:
        name: Build PDF
        runs-on: ubuntu-latest
        container: mcquenji/texlive

        env:
            PDF_NAME: "${{github.repository_owner}} ${{ github.event.repository.name}}" # The name of the compiled PDF file (without the .pdf extension) when a release is created. Change to your heart's content.

        steps:
            - uses: actions/checkout@v3
              with:
                fetch-depth: 0

            - run: git config --global --add safe.directory '*'


            - name: Compile Document
              id: compile
              run: |
                pdflatex --shell-escape -interaction=nonstopmode -halt-on-error main.tex
                makeglossaries main
                pdflatex --shell-escape -interaction=nonstopmode -halt-on-error main.tex
                pdflatex --shell-escape -interaction=nonstopmode -halt-on-error main.tex
        
            - uses: amitsingh-007/next-release-tag@8fab8fd559ffb987e33cf9c3761c219f900d9854
              id: tag
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                tag_prefix: 'v'
                tag_template: dd.mm.yy.i 
            
            - name: Initialize Variables
              id: vars
              run: |
                echo 'versioned-pdf-name="${{ env.PDF_NAME }} ${{ steps.tag.outputs.next_release_tag }}.pdf"' >> $GITHUB_OUTPUT

            - name: Rename PDF
              run: mv main.pdf "${{ steps.vars.outputs.versioned-pdf-name }}"

            - name: Generate Change Log
              uses: mikepenz/release-changelog-builder-action@v4
              id: changelog
              with:
                configuration: .github/workflows/changelog.json
                toTag: ${{ github.sha}}
                fromTag: ${{ steps.tag.outputs.previous_release_tag }}

            - name: Create Release
              uses: ncipollo/release-action@v1.14.0
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                tag: ${{ steps.tag.outputs.next_release_tag }}
                name: PDF Build ${{ steps.tag.outputs.next_release_tag }}
                body: |
                  [Download PDF](https://github.com/${{ github.repository }}/releases/download/${{ steps.tag.outputs.next_release_tag }}/${{ steps.vars.outputs.versioned-pdf-name }})

                  ---

                  ${{ steps.changelog.outputs.changelog}}

                  **Full changelog**: https://github.com/${{ github.repository }}/compare/${{ steps.tag.outputs.previous_release_tag }}...${{ steps.tag.outputs.next_release_tag }}
                artifacts: "${{ steps.vars.outputs.versioned-pdf-name }}"